macro(gen_link_name_for_app)
    if (CMAKE_BUILD_TYPE MATCHES "Debug")
        set(LINK_NAME "${PROJECT_NAME}-d")
    else ()
        set(LINK_NAME "${PROJECT_NAME}")
    endif ()
endmacro()

macro(gen_link_name_for_lib)
    if (CMAKE_HOST_WIN32)
        set(LINK_NAME "lib${PROJECT_NAME}-${PROJECT_VERSION}")
    else ()
        set(LINK_NAME "${PROJECT_NAME}-${PROJECT_VERSION}")
    endif ()

    if (CMAKE_BUILD_TYPE MATCHES "Debug")
        set(LINK_NAME "${LINK_NAME}-d")
    endif ()

    set(LIB_FOR_TEST ${LINK_NAME} CACHE INTERNAL "lib for test")
endmacro()

macro(gen_link_name_for_test)
    if (CMAKE_BUILD_TYPE MATCHES "Debug")
        set(LINK_NAME_FOR_TEST "${PROJECT_NAME}-d")
    else ()
        set(LINK_NAME_FOR_TEST "${PROJECT_NAME}")
    endif ()
endmacro()

macro(use_qt5)
    if (NOT DEFINED CMAKE_BUILD_TYPE)
        MESSAGE(FATAL_ERROR "CMAKE_BUILD_TYPE not defined! It must be defined as 'Debug' or 'Release'!")
    endif ()

    set(CMAKE_SKIP_BUILD_RPATH ON)
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_STANDARD 17)

    set(CMAKE_AUTOUIC ON)
    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTORCC ON)

    set(QT5_COMPONENTS ${ARGN} CACHE INTERNAL "qt5 components")

    foreach (COMP IN LISTS QT5_COMPONENTS)
        find_package(QT NAMES Qt5 COMPONENTS ${COMP} REQUIRED)
        find_package(Qt5 COMPONENTS ${COMP} REQUIRED)
    endforeach ()
endmacro()
macro(link_qt5)
    foreach (COMP IN LISTS QT5_COMPONENTS)
        if (LINK_NAME)
            target_link_libraries(${LINK_NAME} PRIVATE Qt5::${COMP})
        else ()
            target_link_libraries(${PROJECT_NAME} PRIVATE Qt5::${COMP})
        endif ()
    endforeach ()
endmacro()

macro(use_qt5_for_test)
    if (NOT DEFINED CMAKE_BUILD_TYPE)
        message(FATAL_ERROR "CMAKE_BUILD_TYPE not defined! It must be defined as 'Debug' or 'Release'!")
    endif ()

    set(CMAKE_INCLUDE_CURRENT_DIR ON)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_STANDARD 17)

    set(CMAKE_AUTOUIC ON)
    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTORCC ON)

    set(QT5_COMPONENTS_FOR_TEST ${ARGN} CACHE INTERNAL "qt5 components for tests")

    foreach (COMP IN LISTS QT5_COMPONENTS_FOR_TEST)
        find_package(QT NAMES Qt5 COMPONENTS ${COMP} REQUIRED)
        find_package(Qt5 COMPONENTS ${COMP} REQUIRED)
    endforeach ()
endmacro()
macro(link_qt5_for_test)
    foreach (COMP IN LISTS QT5_COMPONENTS_FOR_TEST)
        if (LINK_NAME_FOR_TEST)
            target_link_libraries(${LINK_NAME_FOR_TEST} PRIVATE Qt5::${COMP})
        else ()
            target_link_libraries(${PROJECT_NAME} PRIVATE Qt5::${COMP})
        endif ()
    endforeach ()
endmacro()

macro(link_lib_for_test)
    if (LIB_FOR_TEST)
        if (LINK_NAME_FOR_TEST)
            if (CMAKE_HOST_WIN32)
                target_link_libraries(${LINK_NAME_FOR_TEST} PRIVATE ${LIB_FOR_TEST})
            else ()
                target_link_libraries(${LINK_NAME_FOR_TEST} PRIVATE ${LIB_FOR_TEST})
            endif ()
        endif ()
    endif ()
endmacro()

# todo: include_thirdparty_lib
# todo: link_thirdparty_lib
# todo: use_cbb
# todo: link_cbb
# todo: link_cbb_for_test
# todo: link_lib_for_test

macro(include_thirdparty_lib thirdparty_lib_name)
    include_directories(thirdparty/${thirdparty_lib_name}/include)
endmacro()

macro(link_thirdparty_lib thirdparty_name)
    unset(THIRDPARTY_LIB_NAMES)
    unset(THIRDPARTY_STATIC_LIB_NAMES)

    if (CMAKE_HOST_WIN32)
        if(CMAKE_BUILD_TYPE MATCHES "Debug")
            file(GLOB THIRDPARTY_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/win/debug/*.lib")
        else()
            file(GLOB THIRDPARTY_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/win/release/*.lib")
        endif()
    elseif(CMAKE_HOST_UNIX)
        if(CMAKE_BUILD_TYPE MATCHES "Debug")
            if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "aarch64")
                file(GLOB THIRDPARTY_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/arm64/debug/*.so")
                file(GLOB THIRDPARTY_STATIC_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/arm64/debug/*.a")
                list(APPEND THIRDPARTY_LIB_NAMES ${THIRDPARTY_STATIC_LIB_NAMES})
            else()
                file(GLOB THIRDPARTY_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/x64/debug/*.so")
                file(GLOB THIRDPARTY_STATIC_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/x64/debug/*.a")
                list(APPEND THIRDPARTY_LIB_NAMES ${THIRDPARTY_STATIC_LIB_NAMES})
            endif()
        else()
            if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "aarch64")
                file(GLOB THIRDPARTY_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/arm64/release/*.so")
                file(GLOB THIRDPARTY_STATIC_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/arm64/release/*.a")
                list(APPEND THIRDPARTY_LIB_NAMES ${THIRDPARTY_STATIC_LIB_NAMES})
            else()
                file(GLOB THIRDPARTY_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/x64/release/*.so")
                file(GLOB THIRDPARTY_STATIC_LIB_NAMES "${PROJECT_SOURCE_DIR}/thirdparty/${thirdparty_name}/lib/linux/x64/release/*.a")
                list(APPEND THIRDPARTY_LIB_NAMES ${THIRDPARTY_STATIC_LIB_NAMES})
            endif()
        endif()
    endif()

    if(THIRDPARTY_LIB_NAMES)
        if(LINK_NAME)
            target_link_libraries(${LINK_NAME} PRIVATE ${THIRDPARTY_LIB_NAMES})
        else()
            target_link_libraries(${PROJECT_NAME} PRIVATE ${THIRDPARTY_LIB_NAMES})
        endif()
    endif()
endmacro()

macro(use_cbb cbb_name cbb_version)
    include_directories($ENV{CBB_HOME}/releases/${cbb_name}/${cbb_version}/include)
endmacro()

macro(link_cbb cbb_name cbb_version)
    unset(CBB_LIB_NAMES)
    unset(CBB_DLL_NAMES)
    unset(CBB_PDB_NAMES)
    unset(CBB_STATIC_LIB_NAMES)

    if (CMAKE_HOST_WIN32)
        if(CMAKE_BUILD_TYPE MATCHES "Debug")
            file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/debug/*.lib")
            file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/debug/*.dll")
            file(GLOB CBB_PDB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/debug/*.pdb")
        else()
            file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/release/*.lib")
            file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/release/*.dll")
        endif()
    elseif(CMAKE_HOST_UNIX)
        if(CMAKE_BUILD_TYPE MATCHES "Debug")
            if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "aarch64")
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/debug/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/debug/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/debug/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            else()
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/debug/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/debug/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/debug/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            endif()
        else()
            if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "aarch64")
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/release/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/release/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/release/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            else()
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/release/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/release/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/release/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            endif()
        endif()
    endif()

    if(CBB_LIB_NAMES)
        if(LINK_NAME)
            target_link_libraries(${LINK_NAME} PRIVATE ${CBB_LIB_NAMES})
        elseif(LINK_NAME_FOR_TEST)
            target_link_libraries(${LINK_NAME_FOR_TEST} PRIVATE ${CBB_LIB_NAMES})
        else()
            target_link_libraries(${PROJECT_NAME} PRIVATE ${CBB_LIB_NAMES})
        endif()
    endif()

    # copy cbb dll to build dir.
    if(CBB_DLL_NAMES)
        if(CBB_PDB_NAMES)
            list(APPEND CBB_DLL_NAMES ${CBB_PDB_NAMES})
        endif()

        if(LINK_NAME)
            add_custom_command(TARGET ${LINK_NAME} POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy
                ${CBB_DLL_NAMES}
                $<${PROJECT_NAME}_BINARY_DIR>)
        else()
            add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy
                ${CBB_DLL_NAMES}
                $<${PROJECT_NAME}_BINARY_DIR>)
        endif()
    endif()

endmacro()

macro(link_cbb_for_test cbb_name cbb_version)
    unset(CBB_LIB_NAMES)
    unset(CBB_DLL_NAMES)
    unset(CBB_PDB_NAMES)
    unset(CBB_STATIC_LIB_NAMES)

    if (CMAKE_HOST_WIN32)
        if(CMAKE_BUILD_TYPE MATCHES "Debug")
            file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/debug/*.lib")
            file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/debug/*.dll")
            file(GLOB CBB_PDB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/debug/*.pdb")
        else()
            file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/release/*.lib")
            file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/win/release/*.dll")
        endif()
    elseif(CMAKE_HOST_UNIX)
        if(CMAKE_BUILD_TYPE MATCHES "Debug")
            if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "aarch64")
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/debug/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/debug/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/debug/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            else()
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/debug/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/debug/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/debug/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            endif()
        else()
            if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "aarch64")
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/release/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/release/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/arm64/release/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            else()
                file(GLOB CBB_DLL_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/release/*.so")
                file(GLOB CBB_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/release/*.so")
                file(GLOB CBB_STATIC_LIB_NAMES "$ENV{CBB_HOME}/cbb_releases/${cbb_name}/${cbb_version}/lib/linux/x64/release/*.a")
                list(APPEND CBB_LIB_NAMES ${CBB_STATIC_LIB_NAMES})
            endif()
        endif()
    endif()

    if(CBB_LIB_NAMES)
        if(LINK_NAME_FOR_TEST)
            target_link_libraries(${LINK_NAME_FOR_TEST} PRIVATE ${CBB_LIB_NAMES})
        endif()
    endif()

    # copy cbb dll to build dir.
    if(CBB_DLL_NAMES)
        if(CBB_PDB_NAMES)
            list(APPEND CBB_DLL_NAMES ${CBB_PDB_NAMES})
        endif()

        if(LINK_NAME_FOR_TEST)
            add_custom_command(TARGET ${LINK_NAME_FOR_TEST} POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy
                ${CBB_DLL_NAMES}
                $<${PROJECT_NAME}_BINARY_DIR>)
        else()
            add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy
                ${CBB_DLL_NAMES}
                $<${PROJECT_NAME}_BINARY_DIR>)
        endif()
    endif()
endmacro()

macro(link_lib_for_test)
    if (LIB_FOR_TEST)
        if (LINK_NAME_FOR_TEST)
            if (CMAKE_HOST_WIN32)
                target_link_libraries(${LINK_NAME_FOR_TEST} PRIVATE ${LIB_FOR_TEST})
            elseif(CMAKE_HOST_UNIX)
                target_link_libraries(${LINK_NAME_FOR_TEST} PRIVATE ${LIB_FOR_TEST})
            endif()
        endif()
    endif ()
endmacro()

macro(build_with_windows_subsystem)
    if(WIN32)
        if(LINK_NAME)
            set_target_properties(${LINK_NAME} PROPERTIES LINK_FLAGS "/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup")
        else()
            set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup")
        endif()
    endif()
endmacro()